#include <dlfcn.h>

#define FOREACH_$darwin$(apply) \
    apply(AUGraphAddNode) \
    apply(AUGraphClose) \
    apply(AUGraphConnectNodeInput) \
    apply(AUGraphInitialize) \
    apply(AUGraphNodeInfo) \
    apply(AUGraphOpen) \
    apply(AUGraphSetNodeInputCallback) \
    apply(AUGraphStart) \
    apply(AUGraphStop) \
    apply(AudioObjectGetPropertyData) \
    apply(AudioObjectGetPropertyDataSize) \
    apply(AudioObjectSetPropertyData) \
    apply(AudioOutputUnitStop) \
    apply(AudioUnitSetParameter) \
    apply(AudioUnitSetProperty) \
    apply(AudioUnitUninitialize) \
    apply(DisposeAUGraph) \
    apply(Gestalt) \
    apply(NDR_record) \
    apply(NXCloseEventStatus) \
    apply(NXOpenEventStatus) \
    apply(NewAUGraph) \
    apply(_DefaultRuneLocale) \
    apply(_ZNSt3__115recursive_mutex4lockEv) \
    apply(_ZNSt3__115recursive_mutex6unlockEv) \
    apply(_ZNSt3__115recursive_mutex8try_lockEv) \
    apply(_ZNSt3__115recursive_mutexC1Ev) \
    apply(_ZNSt3__115recursive_mutexC2Ev) \
    apply(_ZNSt3__115recursive_mutexD1Ev) \
    apply(_ZNSt3__115recursive_mutexD2Ev) \
    apply(_ZNSt3__118condition_variable10notify_allEv) \
    apply(_ZNSt3__118condition_variable10notify_oneEv) \
    apply(_ZNSt3__118condition_variable15__do_timed_waitERNS_11unique_lockINS_5mutexEEENS_6chrono10time_pointINS5_12system_clockENS5_8durationIxNS_5ratioILl1ELl1000000000EEEEEEE) \
    apply(_ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE) \
    apply(_ZNSt3__118condition_variableD1Ev) \
    apply(_ZNSt3__118condition_variableD2Ev) \
    apply(_ZNSt3__121recursive_timed_mutex4lockEv) \
    apply(_ZNSt3__121recursive_timed_mutex6unlockEv) \
    apply(_ZNSt3__121recursive_timed_mutex8try_lockEv) \
    apply(_ZNSt3__121recursive_timed_mutexC1Ev) \
    apply(_ZNSt3__121recursive_timed_mutexC2Ev) \
    apply(_ZNSt3__121recursive_timed_mutexD1Ev) \
    apply(_ZNSt3__121recursive_timed_mutexD2Ev) \
    apply(_ZNSt3__15mutex4lockEv) \
    apply(_ZNSt3__15mutex6unlockEv) \
    apply(_ZNSt3__15mutex8try_lockEv) \
    apply(_ZNSt3__15mutexD1Ev) \
    apply(_ZNSt3__15mutexD2Ev) \
    apply(_ZNSt3__16thread4joinEv) \
    apply(_ZNSt3__16thread6detachEv) \
    apply(_ZNSt3__16threadD1Ev) \
    apply(_ZNSt3__16threadD2Ev) \
    apply(__bzero) \
    apply(__cxa_throw) \
    apply(__darwin_check_fd_set_overflow) \
    apply(__error) \
    apply(__exp10f) \
    apply(__maskrune) \
    apply(__sincosf_stret) \
    apply(__stack_chk_guard) \
    apply(__tolower) \
    apply(__toupper) \
    apply(_availability_version_check) \
    apply(_objc_empty_cache) \
    apply(accept) \
    apply(arc4random_buf) \
    apply(asl_close) \
    apply(asl_free) \
    apply(asl_new) \
    apply(asl_open) \
    apply(asl_send) \
    apply(asl_set) \
    apply(bind) \
    apply(bootstrap_look_up) \
    apply(bootstrap_port) \
    apply(bootstrap_strerror) \
    apply(chdir) \
    apply(close$NOCANCEL) \
    apply(closedir) \
    apply(connect) \
    apply(connectx) \
    apply(dispatch_data_create) \
    apply(fork) \
    apply(freeaddrinfo) \
    apply(freeifaddrs) \
    apply(fstat$INODE64) \
    apply(getaddrinfo) \
    apply(getifaddrs) \
    apply(getnameinfo) \
    apply(getpeername) \
    apply(getpwuid) \
    apply(getsockname) \
    apply(getsockopt) \
    apply(glob$INODE64) \
    apply(host_get_exception_ports) \
    apply(host_set_exception_ports) \
    apply(host_statistics) \
    apply(host_swap_exception_ports) \
    apply(if_nametoindex) \
    apply(inet_ntop) \
    apply(inet_pton) \
    apply(kevent) \
    apply(kqueue) \
    apply(kqueuex) \
    apply(lstat$INODE64) \
    apply(mach_absolute_time) \
    apply(mach_error_string) \
    apply(mach_host_self) \
    apply(mach_msg) \
    apply(mach_msg_destroy) \
    apply(mach_port_allocate) \
    apply(mach_port_deallocate) \
    apply(mach_port_extract_right) \
    apply(mach_port_mod_refs) \
    apply(mach_port_request_notification) \
    apply(mach_task_self_) \
    apply(mach_thread_self) \
    apply(mach_timebase_info) \
    apply(memset_pattern16) \
    apply(mmap) \
    apply(objc_alloc) \
    apply(objc_empty_vtable) \
    apply(objc_msgSend) \
    apply(opendir$INODE64) \
    apply(posix_spawn_file_actions_addinherit_np) \
    apply(posix_spawn_file_actions_destroy) \
    apply(posix_spawn_file_actions_init) \
    apply(proc_listpidspath) \
    apply(proc_pidinfo) \
    apply(proc_pidpath) \
    apply(pthread_atfork) \
    apply(pthread_attr_destroy) \
    apply(pthread_attr_getinheritsched) \
    apply(pthread_attr_getschedparam) \
    apply(pthread_attr_init) \
    apply(pthread_attr_setdetachstate) \
    apply(pthread_attr_setinheritsched) \
    apply(pthread_attr_setschedparam) \
    apply(pthread_attr_setschedpolicy) \
    apply(pthread_attr_setstacksize) \
    apply(pthread_cond_broadcast) \
    apply(pthread_cond_destroy) \
    apply(pthread_cond_init) \
    apply(pthread_cond_signal) \
    apply(pthread_cond_timedwait) \
    apply(pthread_cond_wait) \
    apply(pthread_condattr_destroy) \
    apply(pthread_condattr_init) \
    apply(pthread_create) \
    apply(pthread_detach) \
    apply(pthread_equal) \
    apply(pthread_getspecific) \
    apply(pthread_join) \
    apply(pthread_key_create) \
    apply(pthread_key_delete) \
    apply(pthread_mutex_destroy) \
    apply(pthread_mutex_init) \
    apply(pthread_mutex_lock) \
    apply(pthread_mutex_trylock) \
    apply(pthread_mutex_unlock) \
    apply(pthread_mutexattr_destroy) \
    apply(pthread_mutexattr_init) \
    apply(pthread_mutexattr_settype) \
    apply(pthread_once) \
    apply(pthread_rwlock_destroy) \
    apply(pthread_rwlock_init) \
    apply(pthread_rwlock_rdlock) \
    apply(pthread_rwlock_unlock) \
    apply(pthread_rwlock_wrlock) \
    apply(pthread_self) \
    apply(pthread_setname_np) \
    apply(pthread_setspecific) \
    apply(pthread_threadid_np) \
    apply(readdir$INODE64) \
    apply(realpath$DARWIN_EXTSN) \
    apply(recvfrom) \
    apply(res_9_dn_skipname) \
    apply(res_9_query) \
    apply(sched_get_priority_max) \
    apply(sched_get_priority_min) \
    apply(select$1050) \
    apply(semaphore_create) \
    apply(semaphore_destroy) \
    apply(semaphore_signal) \
    apply(semaphore_timedwait) \
    apply(semaphore_wait) \
    apply(sendto) \
    apply(setsockopt) \
    apply(sigaction) \
    apply(stat$INODE64) \
    apply(strlcat) \
    apply(strlcpy) \
    apply(sysctlbyname) \
    apply(task_get_exception_ports) \
    apply(task_info) \
    apply(task_set_exception_ports) \
    apply(task_swap_exception_ports) \
    apply(thread_get_exception_ports) \
    apply(thread_set_exception_ports) \
    apply(thread_swap_exception_ports) \
    apply(uname) \
    apply(uuid_generate) \
    apply(vm_allocate) \
    apply(vm_deallocate) \
    apply(vm_page_size) \
    apply(voucher_mach_msg_set) \
    apply(vsnprintf_l) \
    apply(cgCreateContext) \
    apply(cgDestroyContext) \
    apply(cgSetContextBehavior)

#define declare_external(sym) extern char $darwin$ ## sym[];
FOREACH_$darwin$(declare_external)

void* dlysm_stub_darwin(const char* name) {
    if (!name || strlen(name) > 256) return 0;

    #define find_name(sym) if (0 == strcmp(name, #sym)) return $darwin$ ## sym;
    FOREACH_$darwin$(find_name)

    return 0;
}
